# SPFx Tasks pipeline
# https://devblogs.microsoft.com/premier-developer/ci-cd-with-sharepoint-framework-spfx/

trigger:
- main

variables:
  - name: NodeVersion
    value: '14.x'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NodeVersion)
  displayName: 'install Node.js $(NodeVersion)'

- task: Npm@1
  inputs:
    command: 'install'

- task: gulp@1
  displayName: 'gulp clean'
  inputs:
    gulpFile: '$(Build.SourcesDirectory)/gulpfile.js'
    targets: clean

- task: gulp@1
  displayName: 'gulp build'
  inputs:
    gulpFile: '$(Build.SourcesDirectory)/gulpfile.js'
    targets: build

- task: gulp@1
  displayName: 'gulp bundle --ship'
  inputs:
    gulpFile: '$(Build.SourcesDirectory)/gulpfile.js'
    targets: bundle
    arguments: '--ship'

- task: gulp@1
  displayName: 'gulp package-solution --ship'
  inputs:
    gulpFile: '$(Build.SourcesDirectory)/gulpfile.js'
    targets: 'package-solution'
    arguments: '--ship'

#- script: |
#    gulp clean
#    gulp build
#    gulp bundle --ship
#    gulp package-solution --ship
#  displayName: clean build bundle package

- script: |
    dir
    dir ./sharepoint/solution

- task: CopyFiles@2
  inputs:
     SourceFolder: '$(Build.SourcesDirectory)/sharepoint/solution'
     Contents: 'tasks.sppkg'
     TargetFolder: '$(Build.ArtifactStagingDiretory)/drop'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDiretory)/drop'
    ArtifactName: 'drop'
