# SPFx Tasks pipeline

trigger:
- main

variables:
  - name: NodeVersion
    value: '14.x'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NodeVersion)
  displayName: 'install Node.js $(NodeVersion)'

- task: Npm@1
  inputs:
    command: 'install'

- script: |
    gulp clean
    gulp build
    gulp bundle --ship
    gulp package-solution --ship

- script: |
    dir
    dir ./sharepoint/solution
