# SPFx Tasks pipeline

trigger:
- main

variables:
  - name: NodeVersion
    value: '14.x'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NodeVersion)
  displayName: 'install Node.js $(NodeVersion)'

- task: Npm@1
  inputs:
    command: 'install'

- task: gulp@1
  displayName: 'gulp clean'
  inputs:
    gulpFile: '$(Build.SourcesDirectory)/gulpfile.js'
    targets: clean

- task: Gulp@1
  displayName: 'gulp build'
  inputs:
    gulpFile: '$(Build.SourcesDirectory)/gulpfile.js'
    targets: build

- task: Gulp@1
  displayName: 'gulp bundle'
  inputs:
    gulpFile: '$(Build.SourcesDirectory)/gulpfile.js'
    targets: 'bundle'
    arguments: '--ship'
  continueOnError: true

- task: Gulp@1
  displayName: 'gulp package-solution --ship'
  inputs:
    gulpFile: '$(Build.SourcesDirectory)/gulpfile.js'
    targets: 'package-solution'
    arguments: '--ship'

#- script: |
#    gulp clean
#    gulp build
#    gulp bundle --ship
#    gulp package-solution --ship
#  displayName: clean build bundle package

- task: CopyFiles@2
  displayName: 'Copy files to $(Build.ArtifactStagingDirectory)/drop'
  inputs:
     SourceFolder: '$(Build.SourcesDirectory)'
     Contents: |
       sharepoint/solution/tasks.sppkg
       certificates/*.pfx
       scripts/Deploy-TasksSolution.ps1
     TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/drop'
    artifactName: drop

- script: dir ./scripts
  displayName: 'List scripts'

- script: dir ./sharepoint/solution
  displayName: 'List sharepoint solution'

- script: dir %DROPPATH%
  env:
    DROPPATH: '$(Build.ArtifactStagingDirectory)/drop'
  displayName: 'List drop'
