# SPFx Tasks pipeline

trigger:
- main

variables:
  - name: NodeVersion
    value: '14.x'

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NodeVersion)
  displayName: 'install Node.js $(NodeVersion)'

- task: Npm@1
  inputs:
    command: 'install'

- task: gulp@1
  inputs:
    arguments: 'build'